### PR TITLE
Add tags to metrics

### PR DESCRIPTION
**Pull request by Galbar**
Authors: @michalten and @boarik 

Hi @michalten and @boarik,

I found this branch and you seem to be the authors of the commits. I hope you don't mind me opening the PR. I just wanted to have a place to discuss the status of tagged metrics

Is there any reason why a PR to the main repo was never opened?

Is the work for having tagged metrics finished? Otherwise, what is missing?

Cheers,
Galbar

PD: It seems that this PR would solve #49

### CODE REVIEW

**Comment by boarik** [comment]
Haven't touched this code for a while, but as far as I remember this branch is valid and works.
The maintainer of the upstream repo (omergertel) had no bandwidth to address such a PR and that was the reason we created a separate branch on a separate fork.

**Comment by omergertel** [comment]
Yeah, apologies, I've been swamped and am not an active user of this project anymore (current employer has a different tech stack)

**Comment by Galbar** [comment]
@boarik & @omergertel, thanks for your responses!

I guess I'll have to fork and install that branch

**Comment by Galbar** [comment]
I'm using my fork. I'm closing this PR.

Thanks all :)

**Pull request closed without merging**
